Enhancements to Modal Animations and Functionality for Optimal User Interaction (#87)
* Implement new accordion component for Privacy and Cookie Policies

This commit introduces a new accordion component to enhance the presentation and accessibility of our Privacy and Cookie Policies. This addition is part of our ongoing efforts to improve user experience and provide clear, transparent information regarding user data and privacy.

Key Changes:
- Implemented a new accordion component to dynamically display sections of the Privacy and Cookie Policies, allowing users to expand or collapse information as needed.
- Enhanced the CSS for smooth opening and closing transitions of the accordion, ensuring a fluid user interaction without snappy effects.
- Integrated detailed and structured content into the accordion for both the Privacy Policy and Cookie Policy, ensuring all pertinent information is accessible and easy to navigate.
- Refined introductory texts for both policies to align with our commitment to transparency and to maintain a consistent tone across our platform.
- Added specific CSS styles to the accordion to maintain visual consistency with the rest of the site's design.
- Updated JavaScript logic to handle dynamic `max-height` calculations for the accordion panels, optimizing performance and user experience.

The new accordion component not only improves the aesthetic appeal of the policy sections but also enhances the functionality, making it easier for users to find and understand the information that is most relevant to them.

* Implement modal shake animation on intercepted close attempts (and active popups)

This commit introduces a new feature that enhances the user experience by adding a shake animation to the modal component when a close attempt is intercepted. This visual feedback alerts users that the modal cannot currently be closed due to conditions such as unsaved changes, active popups, or ongoing requests.

Key Changes:
1. Modal Animation CSS: Added 'shake' keyframes and '.shake-animation' class to Modal.module.css to define the shake animation.
2. Modal Component Updates:
   - Added a new boolean prop 'isShaking' to control the animation trigger.
   - Conditionally applied the 'shake-animation' class based on the 'isShaking' state.
3. ModalWrapper Logic:
   - Introduced 'isShaking' state to manage the animation activation.
   - Set 'isShaking' to 'true' upon intercepted close attempts and reset it after the animation duration.
   - Passed 'isShaking' down to the Modal component to control the animation.

This implementation ensures that the modal provides an immediate, clear, and non-disruptive feedback mechanism, making the interface more intuitive and responsive.

* Enhanced modal animations and dynamic resizing support

This commit enhances the modal component with improved animations and dynamic resizing capabilities, improving both aesthetics and functionality.

Key Changes:
1. Animation Enhancements: Refined the 'shake' and 'fade' animations in the CSS to provide smoother transitions for the modal actions. These animations are now applied conditionally based on the modal's state, allowing for more nuanced visual feedback.

2. Dynamic Resizing: Added functionality to adjust the modal's height dynamically based on the viewport changes and content size. This ensures that the modal remains visually appealing and functionally accessible across different devices and orientations.

3. State Management Updates: Updated the ModalWrapper to handle new states for animation control and dynamic resizing. This includes managing states like 'isShaking' and 'isClosing', which help in determining the appropriate animations and adjustments during modal interactions.

4. Code Clean-up: Removed redundant code and optimized existing implementations to enhance performance and maintainability of the modal component.

These updates aim to make the modal component more responsive and adaptable to user interactions and environmental changes, ensuring a seamless user experience.

* lint and format

ran script for cleanup

reminder:

investigatie below to automate...

Run git config user.name github-actions
[54-implement-toast-notifications-and-alert-dialogs-for-enhanced-user-interaction b4a0e73] Apply ESLint and Prettier fixes generated by GitHub Actions
 1 file changed, 20 insertions(+), 16 deletions(-)
remote: Permission to imperfectandcompany/Imperfect-Gamers-Site-Store.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/imperfectandcompany/Imperfect-Gamers-Site-Store/': The requested URL returned error: 403
Error: Process completed with exit code 128.